const mlbStandings = {


    "American League":{
        "AL East": {
            "New York Yankees":{
                "wins": 6,
                "losses": 1,
                "PCT": .857,
                "GB": null,  
                "L10": 6-1,
                "STRK": "w-1",
                "RS": 32,
                "RA": 25,
                "Diff": +7,
                "X-W/L": 4-3,
                "Home": 0-0,
                "Away": 6-1,
                ">500":2-1,
                "Next Game":"April 5 vs. Toronto"
              },

              "Boston Red Sox":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },

              "Baltimore Orioles":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              }, 

               "Tampa Bay Rays":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },

              "Toronto Blue Jays":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },
              
              
        },

    
        "AL Central": {
            "Detroit Tigers":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },
              "Cleveland Guardians":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },
              "Minnesota Twins":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },
              "Kansas City Royals":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },
              "Chicago White Sox":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },
       },
         "AL West": {
            "Los Angeles Angels":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },
              "Teaxs Rangers":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },
              "Seattle Mariners":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },
              "Houston Astros":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },
              "Oakland Athletics":{
                "wins":null,
                "losses":null,
                "PCT":null,
                "GB":null,  
                "L10":null,
                "STRK":null,
                "RS":null,
                "RA":null,
                "Diff":null,
                "X-W/L":null,
                "Home":null,
                "Away":null,
                ">500":null,
                "Next Game":null
              },

    }
},
"National League":{
    "NL East": {
        "Atlanta Braves":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
          "Washington Nationals":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
          "Philadelphia Phillies":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
          "New York Mets":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
          "Miami Marlins":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
    },
    "NL central": {
        "Pittsburgh Pirates":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
          "Milwaukee Brewers":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
          "Chicago Cubs":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
          "Cincinnati Reds":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
          "St.Louis Cardinals":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
    },
    "NL West": {
        "Los Angeles Dodgers":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
          "Arizona Diamondbacks":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
          "San Diego Pirates":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
          "San Francisco Giants":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
          "Colorado Rockies":{
            "wins":null,
            "losses":null,
            "PCT":null,
            "GB":null,  
            "L10":null,
            "STRK":null,
            "RS":null,
            "RA":null,
            "Diff":null,
            "X-W/L":null,
            "Home":null,
            "Away":null,
            ">500":null,
            "Next Game":null
          },
    }


}
}